In [1]:
import numpy as np

In [2]:
a=[2,2,1]
b=(1,2,5)
c=np.array([7,2,3])

In [3]:
for i in a:
    print(i)

2
2
1


In [4]:
a.append(4)
print(a)

[2, 2, 1, 4]


In [5]:
a+=[5]
print(a)

[2, 2, 1, 4, 5]


In [6]:
A=a*2
print(A)

[2, 2, 1, 4, 5, 2, 2, 1, 4, 5]


In [7]:
d=c+2
print(d)

e=c*2
print(e)

[9 4 5]
[14  4  6]


In [8]:
print(a)
B=[]
for i in a:
    B.append(i+i)
    
print(B)

C=[]
for i in a:
    C.append(i*i)
print(C)

[2, 2, 1, 4, 5]
[4, 4, 2, 8, 10]
[4, 4, 1, 16, 25]


In [9]:
x=c**2
y=np.sqrt(c)
z=np.log(c)
print(x)
print(y)
print(z)

[49  4  9]
[2.64575131 1.41421356 1.73205081]
[1.94591015 0.69314718 1.09861229]


# DOT PRODUCTS

In [10]:
a=np.array([1,2])
b=np.array([3,4])

dot=0
for i,j in zip(a,b):
    dot=dot+i*j
    
print(dot)

11


In [11]:
c=a*b
print(c)

print(np.sum(c))
print(c.sum())

[3 8]
11
11


In [12]:
d=np.dot(a,b)
print(d)

11


In [13]:
a.dot(b)

11

# Length of Np array

In [14]:
e=np.linalg.norm(a)
print(e)
f=np.linalg.norm(b)

2.23606797749979


In [15]:
cosang=a.dot(b)/(e*f)
print(cosang)

0.9838699100999074


In [16]:
angle=np.arccos(cosang)
print(angle,"in radians")

0.17985349979247847 in radians


# Matrices

In [17]:
a=np.array([[1,2],[3,4]])
print(a)

b=[[1,2],[3,4]]
print(b)

#To access elements

print(a[0][1])
print(b[0][1])
print(a[0,1])

[[1 2]
 [3 4]]
[[1, 2], [3, 4]]
2
2
2


In [18]:
len(a)

2

In [19]:
m=np.matrix([[1,2],[3,4]])
m

matrix([[1, 2],
        [3, 4]])

In [20]:
m_to_array=np.array(m)
m_to_array

array([[1, 2],
       [3, 4]])

In [21]:
m.T

matrix([[1, 3],
        [2, 4]])

In [22]:
a.T

array([[1, 3],
       [2, 4]])

# Generating Arrays

In [23]:
zeros=np.zeros(5)
print(zeros)

zeros2=np.zeros((3,2))
print(zeros2)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
ones=np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
ran=np.random.random((3,2))
ran

#This gives uniformly distributed numbers between 0 and 1

array([[0.88100134, 0.93976537],
       [0.86053075, 0.08925026],
       [0.12088137, 0.42790079]])

In [26]:
rang=np.random.randn((3,3))
rang

TypeError: 'tuple' object cannot be interpreted as an integer

RANDN function takes individual arguments. OTher functions take tuple as arguments

In [27]:
rang=np.random.randn(3,3)
rang

#This is gaussian distribution with mean 0 and variance 1

array([[-0.46322759, -0.39610629,  0.04402501],
       [-1.65990975,  1.33711115,  0.59206835],
       [ 0.67097161,  0.48961844, -0.08847635]])

In [28]:
print(rang.mean())
print(rang.var())

0.058452730980760946
0.6593484899365512


# Matrix Products

In [29]:
a_inv=np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
a.dot(a_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [31]:
np.linalg.det(a)

-2.0000000000000004

In [32]:
np.diag(a)
np.diag(a_inv)
np.diag(a.dot(a_inv))

array([1., 1.])

# Create a matrix with elements only in the diagonal and all elements are 0

In [33]:
diag=np.diag([1,2,3])
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

If a 2d array is passed to diag, the result is a 1d array of the diagonal elements
If a 2d array is passed to diag, the result is a new matrix with those elements in the diagonal with all others being 0

In [34]:
x=np.array([1,2])
y=np.array([3,4])

In [35]:
#Innter product is same as dot product. Outer product can be found using outer

np.outer(x,y)

array([[3, 4],
       [6, 8]])

In [36]:
#Sum of diagonals
print(np.diag(a).sum())

print(np.trace(a))

5
5


# Eigen values and vectors

In [37]:
a=np.random.random((5,3))

#Each observation is a row. Each column is  a feature

covariance=np.cov(a)
print(covariance.shape)


covariance2=np.cov(a.T)
print(covariance2.shape)

print(covariance2)

#When calculating the covariance of a matrix, transpose it

(5, 5)
(3, 3)
[[ 0.15234729  0.0042714   0.03022432]
 [ 0.0042714   0.04986943 -0.02024061]
 [ 0.03022432 -0.02024061  0.13351828]]


In [38]:
eigen=np.linalg.eig(covariance2)
print(eigen)

eigenh=np.linalg.eigh(covariance2)
print(eigenh)

(array([0.17520064, 0.11650084, 0.04403352]), array([[ 0.79075349,  0.60238606,  0.10881155],
       [-0.07123662,  0.26710743, -0.96103016],
       [ 0.60797554, -0.75218659, -0.25412808]]))
(array([0.04403352, 0.11650084, 0.17520064]), array([[ 0.10881155, -0.60238606, -0.79075349],
       [-0.96103016, -0.26710743,  0.07123662],
       [-0.25412808,  0.75218659, -0.60797554]]))


# Linear Equation

Ax=b
A is matrix
B is vector of values
x is column vector we are finding


A is invertible and its square matrix

A-1 * A * x = A-1 * b

In [39]:
a=np.array(([1,2],[3,4]))
a

array([[1, 2],
       [3, 4]])

In [40]:
b=np.array([4,5])
b

array([4, 5])

In [41]:
x=np.linalg.inv(a).dot(b)
x

array([-3. ,  3.5])

In [42]:
x=np.linalg.solve(a,b)
x

array([-3. ,  3.5])

In [44]:
#p+q=2200
#1.5p+4q=5050


#Solve for p and q

In [45]:
p=np.array(([1,1],[1.5,4]))
q=np.array([2200,5050])

In [46]:
answer=np.linalg.solve(p,q)
answer

array([1500.,  700.])