In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

## Linear Algebra
**linalg**

In [2]:
from scipy import linalg

Determinant of a Matrix

In [3]:
# Compute the determinant of a matrix
linalg.det(A)

3.0

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [7]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [8]:
np.dot(L,U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

We can find out the eigenvalues and eigenvectors of this matrix:

In [9]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Solving systems of linear equations can also be done:

In [12]:
v = np.array([[2],[3],[5]])

In [13]:
v

array([[2],
       [3],
       [5]])

In [14]:
s = linalg.solve(A,v)

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Sparse Linear Algebra
SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.

In [16]:
from scipy import sparse

In [17]:
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))

In [18]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [19]:
A[0,:100] = np.random.rand(100)

In [20]:
A[1,100:200] = A[0,:100]

In [21]:
A.setdiag(np.random.rand(1000))

In [22]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Linear Algebra for Sparse Matrices**

In [23]:
from scipy.sparse import linalg

In [24]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [25]:
A = A.tocsr()

In [26]:
b = np.random.rand(1000)

In [27]:
linalg.spsolve(A, b)

array([ 1.81544677e+02, -2.93169503e+02,  1.34553395e+00,  7.11639473e-01,
        7.67845201e-01,  2.42483031e+00,  3.21763527e-01,  3.23490916e+00,
        9.30898795e-01,  1.88151264e+00,  8.40410101e-01,  7.30316555e-01,
        1.41497885e+00,  1.89197129e+00,  1.84363011e+00,  1.63079622e+00,
        8.14483017e-01,  1.23699847e+00,  9.90569673e-01,  1.05952311e+00,
        5.85480471e-01,  1.78178692e+00,  9.61952701e-01,  9.87751258e-01,
        9.33397867e-01,  4.85850120e+00,  1.03797618e+00,  2.80530179e+00,
        5.77901952e+00,  9.90835942e-01,  1.09479045e+00,  3.26164700e+00,
        5.65997356e-02,  9.99207666e-01,  1.91140424e+00,  6.70773390e-01,
        1.57362568e+00,  9.21969809e-01,  3.48747403e+00,  2.99050610e-01,
        1.21748186e+00,  2.61994720e-01,  6.95343860e-01,  6.34241526e-02,
        1.34391325e-01,  1.17195734e+01,  1.01537851e+00,  6.19704026e-01,
        1.37808607e+00,  1.80619310e-01,  9.90287199e-01,  2.79021922e+00,
        1.11316074e+00,  